baseURL = "https://scrazycarl.github.io/blog_website_trial/"
languageCode = "en-us"
title = "Shizz Academy"
theme = "hyde"
sectionPagesMenu = "main"
publishDir = "scrazycarl.github.io/blog_website_trial/"
